# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20151122_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='regulation_wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
