# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_player_regulation_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='regulation_losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
