# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_auto_20160210_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='regulation_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='regulation_wins',
            field=models.IntegerField(default=0),
        ),
    ]
