# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_auto_20160212_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo_rating',
            field=models.FloatField(default=0),
        ),
    ]
