# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_auto_20160212_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='setid',
            new_name='set_id',
        ),
    ]
