# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger_score', models.IntegerField()),
                ('challengee_score', models.IntegerField()),
                ('parent_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('short_id', models.CharField(default='CHUMP', max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('hometown', models.CharField(default='Parts unknown, Planet Earth', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='challengee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengee_set', to='scores.Player'),
        ),
        migrations.AddField(
            model_name='contest',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_set', to='scores.Player'),
        ),
    ]
