# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_remove_contest_game_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='hometown',
            new_name='origin',
        ),
    ]
