# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20160215_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='game_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        )
    ]
