# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_contest_game_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='challengee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengee_contests', to='scores.Player'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_contests', to='scores.Player'),
        ),
    ]
